# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Members' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.1'
  # Pods for Members
pod 'SDWebImage', '~>3.8'
end
